#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    sumrd=0
    sumld=0
    le=len(arr)

    for i in range (le):
        for j in range(le):
            if (i==j):
                sumrd+=(arr[i][j])

            if(i==le-j-1):
                sumld+=(arr[i][j])
    
    sub=sumld-sumrd
    return abs(sub)



    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
